#!/bin/bash

echo "compiling for simulator.."
avr-gcc \
  src/*.c \
  src/Misc/*.c \
  src/Models/*.c \
  src/EventSystem/*.c \
  src/EventSystem/wraps/*.c \
  -ffunction-sections -fdata-sections \
  -Wl,--gc-sections -Os -flto \
  -Wall -Wextra -Wfatal-errors \
  -D SIMULATOR \
  -D F_CPU=16000000 -mmcu=atmega328p -o main
