#!/bin/bash

echo "HI"

echo compiling..
avr-gcc "$@" -DF_CPU=16E6 -Os -Wall -Wextra -mmcu=atmega328p -o main

echo extracting hex..
avr-objcopy -O ihex main main.hex

echo flashing..
avrdude -p atmega328p -c arduino -P /dev/ttyACM0 -b 115200 -U flash:w:main.hex:i
