#include "Vector.h"

DEFINE_VECTORS(char)
DEFINE_VECTORS(uchar)
DEFINE_VECTORS(short)
DEFINE_VECTORS(ushort)
DEFINE_VECTORS(int)
DEFINE_VECTORS(uint)
DEFINE_VECTORS(long)
DEFINE_VECTORS(ulong)
DEFINE_VECTORS(bool)
DEFINE_VECTORS(float)
DEFINE_VECTORS(double)