#include "io.h"

#define DEFINE_REGISTER(NAME) \
volatile uint8_t NAME = 0;

#define DEFINE_PIN(NAME, VALUE) \
volatile uint8_t NAME = VALUE;

#define DEFINE_REGISTERS(NAME) \
DEFINE_REGISTER(_ddr##NAME) \
DEFINE_REGISTER(_port##NAME) \

#define DEFINE_PINS(NAME, VALUE) \
DEFINE_PIN(_dd##NAME, VALUE) \
DEFINE_PIN(_port##NAME, VALUE) \

DEFINE_REGISTERS(b)
DEFINE_REGISTERS(c)
DEFINE_REGISTERS(d)

DEFINE_PINS(b0, 0)
DEFINE_PINS(b1, 1)
DEFINE_PINS(b2, 2)
DEFINE_PINS(b3, 3)
DEFINE_PINS(c0, 0)
DEFINE_PINS(c1, 1)
DEFINE_PINS(c2, 2)
DEFINE_PINS(d4, 4)
DEFINE_PINS(d7, 7)

DEFINE_PIN(_pd5, 5)
DEFINE_PIN(_pd6, 6)
DEFINE_PIN(_admux, 0)
DEFINE_PIN(_refs0, 0)
DEFINE_PIN(_adcsra, 0)
DEFINE_PIN(_adps0, 0)
DEFINE_PIN(_adps1, 1)
DEFINE_PIN(_adps2, 2)
